services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: always
    environment:
      - JENKINS_OPTS="--httpPort=8080"
      - DOCKER_HOST=tcp://dind:2375
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
    expose:
      - "8080"

  dind:
    image: docker:24-dind
    privileged: true
    command: --host=tcp://0.0.0.0:2375
    environment:
      - DOCKER_TLS_CERTDIR=
    volumes:
      - dind_storage:/var/lib/docker
    expose:
      - "2375"

volumes:
  jenkins_home:
  dind_storage:
